feat: Add sanitizer for tiktok
svenjacobs/leon pull request #310
Opened 2023-10-24 18:47 UTC by yedayak

Note some sharing interfaces in the app give you shortened links (like https://vt.tiktok.com/fr54gr6rf3e) that expand to the links matched here, but there isn't infrastructure in the app currently to deal with them.

2023-10-25 11:41 UTC, svenjacobs requested changes
Thanks for your pull request 😃 I have a few remarks.

2023-10-25 11:41 UTC, svenjacobs commented on core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/tiktok/TiktokSanitizer.kt
> +	override val id = SanitizerId("Tiktok")
The ID value should be lowercase.

2023-10-25 11:41 UTC, svenjacobs commented on core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/tiktok/TiktokSanitizer.kt
> +	)
There is no need to use a regex here.

```suggestion
	override fun matchesDomain(input: String) = input.matchesDomain(
		domain = "tiktok.com",
	)
```

2023-10-25 11:41 UTC, svenjacobs commented on core-domain/src/main/res/values/strings.xml
> +    <string name="sanitizer_tiktok_name" translatable="false">Tiktok</string>
The official wording is `TikTok`

```suggestion
    <string name="sanitizer_tiktok_name" translatable="false">TikTok</string>
```

2023-10-25 11:41 UTC, svenjacobs commented on core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/tiktok/TiktokSanitizerTest.kt
Please fix the formatting of this file with

```
./gradlew formatKotlin
```

2023-10-25 11:42 UTC, svenjacobs commented
> Note some sharing interfaces in the app give you shortened links (like https://vt.tiktok.com/fr54gr6rf3e) that expand to the links matched here, but there isn't infrastructure in the app currently to deal with them.

That is correct. Leon would have to perform network requests to unwrap these short URLs which is [not desired](https://github.com/svenjacobs/leon/discussions/80).

2023-10-26 19:31 UTC, yedayak commented on core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/tiktok/TiktokSanitizer.kt
> +	override val id = SanitizerId("Tiktok")
Done

2023-10-26 19:31 UTC, yedayak commented on core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/tiktok/TiktokSanitizer.kt
> +	)
Changed

2023-10-26 19:45 UTC, svenjacobs approved these changes
LGTM. Thank you very much!

2023-10-26 19:46 UTC, merged

2023-10-26 19:46 UTC, svenjacobs commented
@all-contributors please add @yedayak for code